name: Deploy landing.poz.world

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions: write-all

jobs:
  build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build the App

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false
          fetch-depth: 0

      - uses: poz-world/minver@main
        name: MinVer
        id: minver
        with:
          auto-increment: patch
          build-metadata: ${{ github.sha }}
          default-pre-release-identifiers: preview.0
          minimum-major-minor: 0.0
          tag-prefix: 'v'
          verbosity: info

      # - name: Debug Environment
      #   run: |
      #     echo "PATH: $PATH"
      #     echo "SHELL: $SHELL"
      #   shell: bash

      # - name: Set Path env var
      #   run: Write-Output $(Join-Path -Path $(Get-Location) -ChildPath "PATH=node_modules/.bin:$env:PATH") >> $GITHUB_ENV
      #   shell: pwsh

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://npm.pkg.github.com/
          token: ${{ secrets.HIVCHASER_PACKAGES_PAT }}
          always-auth: true

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.com

      - name: Install TypeScript
        run: npm install typescript --force || true

      - name: build
        run: npm run build:production
        env:
          REACT_APP_VERSION: ${{ steps.minver.outputs.version }}
          REACT_APP_PUBLIC_URL: https://landing.poz.world
          REACT_APP_MASTODON_URL: https://poz.world
          CI: 'false'

      - name: Upload artifacts
        uses: actions/upload-artifact@v4.4.3
        with:
          name: build
          path: build
          
  deploy-to-azure-static-website:
    runs-on: ubuntu-latest
    name: Deploy to Azure Static Website
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: build
          
      - name: Deploy to Azure Static Website
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.POZ_WORLD_LANDING_DEPLOYMENT_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "." # App source code path
          api_location: "" # Api source code path - optional
          output_location: "." # Built app content directory - optional
          skip_app_build: true
          ###### End of Repository/Build Configurations ######

  deploy-to-azure-storage:
    runs-on: ubuntu-latest
    name: Deploy to Azure Storage
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: build
      - uses: LanceMcCarthy/Action-AzureBlobUpload@v3.2.0
        with:
          connection_string: ${{ secrets.POZ_WORLD_AZURE_STORAGE_CONNECTION_STRING }}
          container_name: landing
          source_folder: ./
          destination_folder: / # optional
          clean_destination_folder: true # optional
          fail_if_source_empty: true # optional
          is_recursive: true # optional, default is true
          delete_if_exists: true # optional

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.POZ_WORLD_LANDING_DEPLOYMENT_TOKEN }}
          action: "close"
          app_location: "."
