# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish Node.js Package

on:
  release:
    types: [created]

jobs:
  # build:
    # runs-on: ubuntu-latest
    # steps:
    #   - uses: actions/checkout@v4
    #   - uses: actions/setup-node@v4
    #     with:
    #       node-version: 22
    #   - run: npm ci
    #   - run: npm test

  publish-gpr:
    # needs: build
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: poz-world/minver@main
        id: minver
      - uses: poz-world/update-package-version@main
        with:
          version: ${{ steps.minver.outputs.version }}
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://npm.pkg.github.com/
          token: ${{ secrets.HIVCHASER_PACKAGES_PAT }}
          always-auth: true
        env:
          PATH: ./node_modules/.bin:${{ env.PATH }}
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.com
      # - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.HIVCHASER_PACKAGES_PAT}}
          REACT_APP_VERSION: ${{ steps.minver.outputs.version }}
